### PR TITLE
Develop optix

### PR DESCRIPTION
**Pull request by asemlucben**

### CODE REVIEW

**Comment by asemlucben** [comment]
Please delete this request, it was made by mistake

**Comment by S-Gilk** [comment]
Hi Luca,
No problem. Curious what you are working on with this? By the way, the most recent code I wrote was in the web-server branch. Cleaned up the project and added a third container image build for a web server.

**Comment by asemlucben** [comment]
Hi, i was trying to use this code to pack an FT Optix application inside a Docker container and then executing it in the CTRLX Core module. I was actually pulling information from the web-server branch

**Comment by S-Gilk** [comment]
Are you working with Carl Bostrom on this? If you have any questions feel free to reach out to me. We could also package this as a snap to run directly on the ctrlX CORE without virtualization in the Docker engine.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by S-Gilk** [comment]
FYI I just merged back to main and added a .deb file I forgot to push to repo.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by asemlucben** [comment]
Yes, i am working with Mauro and Carl but at the moment we didn't have time to schedule a meeting, if you have 5 mins we can get in touch and I can show you my result, I am in the debugging step, the snap was uploaded to the module but I can't understand how to execute that. You can contact me at [name].[lastname]@rockwellautomation.com

**Comment by asemlucben** [comment]
Hi  @S-Gilk i contacted the GitHub team and they said they can only delete the pull request if you explicitly write that you aggree that here, can you please be so kind to do so?

**Comment by S-Gilk** [comment]
Hello GitHub team,
I agree to delete this pull request from this repo.
Thanks!

**Comment by asemlucben** [comment]
Thank you so much!

**Pull request closed without merging**
